name: JFrog CI with Maven

on:
  push:
    branches: [ nr ]
  workflow_dispatch:

# Set env. variables
env:
  IMAGE_NAME: petclinic
  DOCKER_REGISTRY: ${{ secrets.JF_DOCKER_REGISTRY }}
  DOCKER_REPO: petclinic-docker-local                   # Artifactory Docker local repo
  # env variables for New Relic Java Agent
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  NEW_RELIC_APP_NAME: SpringPetClinic-Docker
  NEW_RELIC_LOG_FILE_NAME: STDOUT

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Compile, Test and Packing
      - name: Build with Maven Wrapper
        run: ./mvnw -B clean verify

      # 4.1. Download New Relic Java Agent
      # Before starting the Docker build, download the agent and unzip it into a 'newrelic' folder within the build context (current folder).
      - name: Prepare New Relic Agent
        run: |
          curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
          unzip newrelic-java.zip
          rm newrelic-java.zip

      # 5. Build Docker image
      # the 'newrelic' folder is in context. COPY it from our Dockerfile.
      - name: Build Docker image
        run: |
          docker build \
            -t $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:${{ github.sha }} \
            -t $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:latest \
            .

      # 6. Docker login to JFrog (Access Token recommended)
      - name: Docker login to JFrog
        run: |
          echo "${{ secrets.JF_ACCESS_TOKEN }}" | docker login $DOCKER_REGISTRY \
            -u "${{ secrets.JF_USERNAME }}" --password-stdin

      # 7. Push Docker image
      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:${{ github.sha }}
          docker push $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:latest