name: JFrog CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
# Set env. variables
env:
  IMAGE_NAME: petclinic
  DOCKER_REGISTRY: ${{ secrets.JF_DOCKER_REGISTRY }}
  DOCKER_REPO: petclinic-docker-local                   # Artifactory Docker local repo

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Compile, Test and Packing
      - name: Build with Maven Wrapper
        run: ./mvnw -B clean verify

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:${{ github.sha }} \
            -t $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:latest \
            .

      # 6. Docker login to JFrog (Access Token recommended)
      - name: Docker login to JFrog
        run: |
          echo "${{ secrets.JF_ACCESS_TOKEN }}" | docker login $DOCKER_REGISTRY \
            -u "${{ secrets.JF_USERNAME }}" --password-stdin

      # 7. Push Docer image to JFrog Artifactory
      - name: Push Docker images
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:${{ github.sha }}
          docker push $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:latest